server:
  port: 8088

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:~/h2db/db/spring-security6-demo;MODE=MYSQL;AUTO_SERVER=TRUE
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      platform: h2
      data-locations: classpath:sql/data.sql
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false