spring:
  security:
    oauth2:
      client:
        meta:
          apple:
            team-id: your-apple-team-id
            key-id: your-apple-key-id
            issuer: https://appleid.apple.com
        registration:
          kakao:
            client-id: your-client-id
            client-secret: your-client-secret
            scope: email, name
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/authorized/{registrationId}"
          naver:
            client-id: your-client-id
            client-secret: your-client-secret
            scope: email, name
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/authorized/{registrationId}"
          apple:
            client-id: your-client-id
            scope: email, name
            client-name: apple
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/authorized/{registrationId}" # apple supports https only
        provider:
          # https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#req-user-info
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          # https://developers.naver.com/docs/login/devguide/devguide.md#2-2-1-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          # https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub
            issuer-uri: https://appleid.apple.com


